server.port=8873
spring.application.name=agent-app
server.servlet.context-path=/agent-app

##------------------------------------------------------ Swagger configuration ---------------------####
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/docs
springdoc.server-url=https://alpha.teamboost.ai/agent-app

##------------------------------------------------------ Agent nodes configuration ---------------------####
#com.aimanager.fetch.data.node.id=101
downstream.task.conversation.graph.id=1
downstream.task.conversation.graph.commit.id=1

##------------------------------------------------------ SQL database configuration ----------------####
spring.datasource.url=jdbc:postgresql://postgres-db-aimanager:5432/aimanager
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

##------------------------------------------------------ SQL database configuration -------------------####

####---------------------------------------------------- TeamBoost cassandra configuration-------------####

spring.data.cassandra.keyspace-name=agent_memory_test
spring.data.cassandra.contact-points=agent-local-cassandra
spring.data.cassandra.port=9042
spring.data.cassandra.local-datacenter=datacenter1

####---------------------------------------------------- TeamBoost cassandra configuration--------------####
