server.port=8872
spring.application.name=graph-builder
server.servlet.context-path=/graph-builder

##------------------------------------------------------ Swagger configuration ------------####
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/docs
springdoc.server-url=https://alpha.teamboost.ai/graph-builder

##------------------------------------------------------ SQL database configuration ------------####
spring.datasource.url=jdbc:postgresql://postgres-db-aimanager:5432/aimanager
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

####---------------------------------------------------- TeamBoost cassandra configuration------####

spring.data.cassandra.keyspace-name=agent_memory_test
spring.data.cassandra.contact-points=agent-local-cassandra
spring.data.cassandra.port=9042
spring.data.cassandra.local-datacenter=datacenter1

####---------------------------------------------------- TeamBoost cassandra configuration------####

##------------------------------------------------------ Agent nodes configuration ---------------------####
#com.aimanager.fetch.data.node.id=101
downstream.task.conversation.graph.id=1
downstream.task.conversation.graph.commit.id=1

####----------------------------------------------------AIManager data load Configurations------------------------------------------####

spring.web.resources.static-locations=/app/uploads
com.aimanager.files.location=/app/uploads

com.aimanager.server.attachments=https://alpha.teamboost.ai/graph-builder/attachments/download?uf=

server.tomcat.max-swallow-size=-1
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=35MB

# Maximum files allowed per item : current value is 5
com.aimanager.limit.uploaded.item.files=5

####----------------------------------------------------firebase Configurations------------------------------------------####

