
spring.data.cassandra.keyspace-name=agent_memory_test
spring.data.cassandra.contact-points=127.0.0.1,172.21.0.3,agent-local-cassandra,agent-local-cassandra/172.21.0.3
spring.data.cassandra.port=8871
spring.data.cassandra.local-datacenter=datacenter1
com.hippo.cassandra.local.config.file=docker-cu-cassandra.yaml