server.port=9091
server.servlet.context-path=/agent-memory

springdoc.swagger-ui.path=/docs


####---------------------------------------------------- TeamBoost cassandra configuration------------------------------------------####

spring.data.cassandra.keyspace-name=agent_memory_test
spring.data.cassandra.contact-points=127.0.0.1
spring.data.cassandra.port=7012
spring.data.cassandra.local-datacenter=datacenter1

####---------------------------------------------------- TeamBoost cassandra configuration------------------------------------------####
