spring.application.name=aimanager
server.servlet.context-path=/aimanager
server.port=8082

##------------------------------------------------------ SQL database configuration ------------
spring.datasource.url=jdbc:postgresql://localhost:5439/aimanager
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

##------------------------------------------------------ SQL database configuration ------------

#swagger configuration
springdoc.swagger-ui.path=/docs
